### ISSUE TITLE
フロントエンド - HTML/HTML5 - 文章構造

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#18]
### ■目的

HTML5で新しく定義された文章構造について理解し、実際に作成したフォームに適用します。

### ■課題1

以下の文章構造タグについて調べて下さい。

- header
- footer
- article
- nav
- aside
- section

### ■課題2

作成したフォームに対し、文章構造タグを適用して下さい。

**Comment by thori0908** [comment]
#### header
#### footer
#### article
#### nav
#### aside
#### section

**Comment by fr-itaya** [comment]
課題1確認しました!:+1:

**Comment by fr-matsuo** [comment]
課題1確認しました、OKです。

**Comment by fr-sasaki** [comment]
こちらクローズします
