### ISSUE TITLE
フロントエンド - CSS - CSSを理解する

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#19]
### ■目的

CSSの概念や記述方法などを理解します。

### ■課題

以下について調べてIssueに記述して下さい。

- CSSとは
- CSSの記述要素
 - 宣言ブロック
 - セレクタ
 - id
 - class
 - プロパティ
- idとclassの違い

**Comment by thori0908** [comment]
#### CSSとは
#### CSSの記述要素
 #### 宣言ブロック
 #### セレクタ
 #### id
 #### class
 #### プロパティ
#### idとclassの違い

**Comment by fr-itaya** [comment]
確認しました！大丈夫ですー:coffee:

**Comment by fr-matsuo** [comment]
OKです!
