### ISSUE TITLE
フロントエンド - CSS - CSSを用いたレイアウト

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#20]
### ■目的

CSSを用いて作成したフォームのレイアウトを変更します。

### ■課題

`style`タグを用いて以下のレイアウトを対応して下さい。

- ヘッダーの上下に余白を10px付ける
- ヘッダーのフォントサイズを30pxにする
- ヘッダーの背景色を変更する(色は自由)
- フォーム画面の項目名の文字色を変更する(色は自由)
- 確認画面の表組みに線を表示する
- 完了画面の文言を強調表示する

**Comment by thori0908** [comment]
Ref.
http://www.htmq.com/csskihon/004.shtml

**Comment by fr-sasaki** [comment]
クローズします！
