### ISSUE TITLE
データベース - MySQL - DB作成

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#23]
### ■目的

SQLを用いてDBを作成、操作します。  
発行したコマンドとその結果はIssueに記述して下さい。

### ■課題1

MySQLコマンドからMySQLサーバに接続し、以下を満たすDBを作成して下さい。DB名はお任せします。  
作成後はDB一覧を表示して作成されたかどうかを確認して下さい。

- 文字コード:UTF-8

### ■課題2

もう1つDBを作成し、作成したDBに切り替え、切り替えられたかどうかまで確認をして下さい。

### ■課題3

課題2で作成したDBを削除して下さい。

**Comment by thori0908** [comment]
``
$ mysql -u root
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 213
Server version: 5.5.40-log MySQL Community Server (GPL)

Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
mysql> create database utfDB default character set utf8;
Query OK, 1 row affected (0.00 sec)
``

**Comment by fr-itaya** [comment]
課題1ですが、「DB一覧を表示」して作成されたかどうかの確認までお願いします！
それ以外はOKですー

**Comment by thori0908** [comment]
#### 課題1
```
$ mysql -u root
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 213
Server version: 5.5.40-log MySQL Community Server (GPL)

Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

mysql> create database utfDB default character set utf8;
Query OK, 1 row affected (0.00 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| firstDB            |
| mysql              |
| performance_schema |
| test               |
| utfDB              |
+--------------------+
6 rows in set (0.00 sec)
```

#### 課題2
```
mysql> create database anotherDB;
Query OK, 1 row affected (0.00 sec)

mysql> connect anotherDB
Connection id:    217
Current database: anotherDB
```

#### 課題3
```
mysql> drop database anotherDB;
Query OK, 0 rows affected (0.01 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| firstDB            |
| mysql              |
| performance_schema |
| test               |
| utfDB              |
+--------------------+
6 rows in set (0.00 sec)
```

Ref.
http://www.yukun.info/blog/2008/10/mysql-login-user-create-database.html
http://doremi.s206.xrea.com/mysql/
http://mysql.javarou.com/dat/000575.html

**Comment by fr-matsuo** [comment]
確認しました、OKです!

**Comment by fr-itaya** [comment]
確認しました、OKですー。お疲れ様でした！
