### ISSUE TITLE
データベース - MySQL - アカウント作成

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#24]
#### ■目的

SQLを用いてアカウントを作成します。

#### ■課題

以下の権限を持つアカウントをSQLを用いて作成して下さい。  
アカウント名、パスワードはお任せしますがアカウント名は分かり易い、パスワードは複雑性のあるものにして下さい。  
作成の際に発行したコマンドとその結果はIssueに記述して下さい。(パスワードは****と伏せて記述して下さい)

- グローバルレベルで全権限を持つアカウント
- データベースレベルでSELECT権限のみを持つアカウント(DBは先ほど作成したものを指定)
- データベースレベルでCREATE, ALTER, SELECT, DELETE権限を持つアカウント(DBは先ほど作成したものを指定)

**Comment by thori0908** [comment]
Ref.
http://www.dbonline.jp/mysql/user/index1.html

**Comment by fr-itaya** [comment]
###### 共通
ユーザーを作成した後はユーザー一覧を、権限の付与を行った後はユーザーの持つ権限の確認を必ず行いましょう。

###### 「グローバルレベルで全権限を持っているアカウント」
ここでいうグローバルレベルとは、「全てのDBに対する権限」という意味になります。  
現在の記述では、`utfDB`というデータベースレベルで全権限を持っていることになっています。

**Comment by thori0908** [comment]
- アカウント作成
```
mysql> create user 'user1'@'localhost' identified by 'password';
Query OK, 0 rows affected (0.00 sec)

mysql> create user 'user2'@'localhost' identified by 'password';
Query OK, 0 rows affected (0.00 sec)

mysql> create user 'user3'@'localhost' identified by 'password';
Query OK, 0 rows affected (0.00 sec)
```
- グローバルレベルで全権限を持つアカウント
```
mysql> grant all on *.* to 'user1'@localhost identified by 'password';
Query OK, 0 rows affected (0.01 sec)
```
- データベースレベルでSELECT権限のみを持つアカウント(DBは先ほど作成したものを指定)
```
mysql> grant select on utfDB.* to 'user2'@localhost identified by 'password';  
Query OK, 0 rows affected (0.00 sec)
```
- データベースレベルでCREATE, ALTER, SELECT, DELETE権限を持つアカウント(DBは先ほど作成したものを指定)
```
mysql> grant create,alter,select,delete on utfDB.* to 'user3'@localhost identified by 'password';
Query OK, 0 rows affected (0.00 sec)
```
Ref.
http://www.dbonline.jp/mysql/user/index1.html
http://www.dbonline.jp/mysql/user/index5.html
http://qiita.com/pinohara/items/481c95dc4c8c2568bf8d
http://ftp.nchu.edu.tw/MySQL/doc/refman/5.1/ja/grant.html

**Comment by fr-matsuo** [comment]
確認しました、OKです!

**Comment by fr-itaya** [comment]
確認しました、OKです。お疲れ様でしたー。
