### ISSUE TITLE
データベース - MySQL - テーブル作成

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#25]
### ■目的

SQLを用いてテーブル作成、操作を学びます。  
課題毎に発行したコマンドをIssueに記述して下さい。

### ■課題1

作成したDBに対し、以下を満たすテーブルを作成して下さい。

- ストレージエンジン:InnoDB
- 文字コード:UTF-8
- テーブル構成

| カラム名 | 型 | NULL可 |
|----|---|---|
| id | INT | NO |
| title | VARCHAR(32) | YES |
| note | TEXT | YES |
| created_at | DATETIME | NO |

### ■課題2

作成したテーブルを削除し、IDをプライマリーキーにして再作成して下さい。

### ■課題3

テーブル削除、再作成をせずに以下のカラム追加、変更、削除をして下さい。

- titleの次に以下のカラムを追加
 - カラム名：editor 型：VARCHAR(16) NULL可：YES
- titleのNULL可をNOに変更
- noteを削除

### ■課題4

以下のテーブルを別に作成し、課題1で作成したテーブルを親として外部キー制約を追加して下さい。

| カラム名 | 型 | NULL可 |
|----|---|---|
| id | INT | NO |
| detail | TEXT | YES |

### ■課題5

課題4で作成したテーブルを削除して下さい。削除後は次の課題で使うので再度テーブルを作成して下さい。

**Comment by thori0908** [comment]
create table kadai1

**Comment by fr-itaya** [comment]
確認しました！OKです！

###### テーブル情報の確認について
`DESCRIBE`だと文字モードやストレージエンジンが表示されないので、テーブル情報の確認には`SHOW CREATE TABLE tablename;`もよく使います。合わせて覚えておきましょう！

**Comment by fr-matsuo** [comment]
確認しました、OKです!


###### SQL文について
SQL文は`;`を入力するまで解釈されないため、複数行に分けたり、インデントを入れることが可能です。

削除など、特に慎重な発行が求められる際は、予めメモ帳などに記述して整え、
確認後にコピペするという方法をとると、安全でログも見やすくなります。
