### ISSUE TITLE
データベース - MySQL - DB設計ツール

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#28]
以下のテーブルをDB設計ツールを用いて設計してもらいます。

■ユーザー情報

日本語名|カラム名|型
---|---|---
ユーザーID|user_id|INT
姓|last_name|TEXT
名|first_name|TEXT
メールアドレス|email|varchar(255)
都道府県ID|pref_id|INT
登録日時|created_at|datetime
更新日時|updated_at|timestamp

■都道府県情報
 
日本語名|カラム名|型
---|---|---
都道府県ID|pref_id|INT
都道府県名|pref_name|TEXT

--

### ■目的

MySQL Workbench を用いてDB設計、SQL化を学びます。

### ■課題1

公式サイトからMySQL Workbenchをインストールして下さい。

### ■課題2

MySQL Workbenchを使って課題のテーブルを持つDBを構築して下さい。    
構築する際には正規化、外部キー制約など考慮して構築して下さい。  
構築し終えたら以下をIssueのコメントに記載、添付して下さい。

- SQL展開したSQL文
- DB設計のキャプチャ

**Comment by thori0908** [comment]
#### 課題1
Ref. 
http://php-tips.com/2011/05/23/mysql-workbench-with-ssh-connection/

**Comment by fr-itaya** [comment]
確認しました、一部共有漏れがあり申し訳ないですが、下記ご対応よろしくお願いいたします！
- テーブルの主キーにはそれぞれ`AUTO_INCREMENT`を付けましょう。
- 都道府県名はNULL不可にしましょう。
- userテーブルのupdated_atもNULL不可にしましょう。
- userテーブルにlast_nameのカラムが抜けています。
- emailの型が異なります。`VARCHAR(255)`に修正しておきましょう。
- userテーブルのDEFAULT CHARACTER SETは`utf8`にしましょう。
- テーブル名の命名規則は以下の通りです。
  - 中間テーブル以外の場合：複数形`users`
  - 中間テーブルの場合：紐付くテーブル名を連結`content_tag`(contentsテーブルとtagsテーブルの中間テーブルの場合)

**Comment by fr-matsuo** [comment]
`AUTO_INCREMENT` について少し補足です。

主キーに`AUTO_INCREMENT`を付与すると、値が連番で付与されるようになります。
この連番は、過去に付与した最大値+1 となるため、削除したレコードとも重複しない主キーを付与できます。

また、最大値をDBが保持しているため、走査する必要が無く、
走査～挿入までに他のレコードが挿入される、といった事態も防ぐことができます。

**Comment by thori0908** [comment]
#### 課題1

#### 課題2
```
-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 18:50:56 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema issue28
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema issue28
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `issue28` DEFAULT CHARACTER SET utf8 ;
USE `issue28` ;

-- -----------------------------------------------------
-- Table `issue28`.`prefectures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue28`.`prefectures` (
  `pref_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pref_name` TEXT NOT NULL,
  PRIMARY KEY (`pref_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `issue28`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `issue28`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `last_name` TEXT NULL DEFAULT NULL,
  `first_name` TEXT NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `pref_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `pref_id`),
  INDEX `fk_user_prefecture_idx` (`pref_id` ASC),
  CONSTRAINT `fk_users_prefectures`
    FOREIGN KEY (`pref_id`)
    REFERENCES `issue28`.`prefectures` (`pref_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

```

**Comment by fr-itaya** [comment]
確認しました、OKです:+1:

**Comment by fr-matsuo** [comment]
確認しましたOKです!
