### ISSUE TITLE
サーバサイド - PHP - フォーム登録

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#29]
### ■目的

PHPからDBへの接続と操作について学びます。

### ■課題

完了画面に遷移した際に、DBへ接続しフォームの値を登録して下さい。  
フォーム値はPOSTで送信し、DB設計は下記を参考にして下さい。  
https://github.com/fact-real/developers_training_public/wiki/%E9%96%8B%E7%99%BA%E7%A0%94%E4%BF%AE-db%E8%A8%AD%E8%A8%88%E3%83%84%E3%83%BC%E3%83%AB#mysql-workbench

PHPからのMySQL接続などはPDOを用いて実装して下さい。
http://www.php.net/manual/ja/pdo.construct.php

**Comment by fr-matsuo** [comment]
#53 で完了したのでクローズします。
