### ISSUE TITLE
サーバサイド - PHP - オブジェクト指向

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#30]
### 概要
クラスベースのオブジェクト指向について学びます。

### 目的
クラスベースのオブジェクト指向を用いてプログラミングができるようになる。

適切にファイルを分割し、ソースコードのメンテナンス性を高めることができる。

#### 課題1
下記用語について調べてください。
- オブジェクト
- クラス
 - プロパティ
 - メソッド
 - コンストラクタ/デストラクタ
 - カプセル化
- インスタンス化
- アクセス修飾子
- abstract修飾子
- staticキーワード
- getter/setter
- 継承
 - オーバーライド
 - parent

#### 課題2
下記制御構造について調べてください。
- require
- require_once
- include
- include_once

#### 課題3
※ここからは「サーバサイド - PHP - フォーム作成」の課題で作成したフォームを使用します。

例を参考に、制御構造を用いて各画面2ファイル以上に分割してください。

#### (例

- confirm.php(元ファイル)
```php
<?php
function fullName($last_name, $first_name) {
    return sprintf('%s %s', $last_name, $first_name);
}

$full_name = fullName($_POST['last_name'], $_POST['first_name']);
?>
<html>
～ 省略 ～
名前：<?php echo $full_name ?>
～ 省略 ～
</html>
```
#### ↓2分割後

- confirm.php(元ファイルからphpのロジック部を切り出したファイル)
```php
<?php
function fullName($last_name, $first_name) {
    return sprintf('%s %s', $last_name, $first_name);
}

$full_name = fullName($_POST['last_name'], $_POST['first_name']);

include 'profile.html.php';
```

- confirm.html.php(元ファイルからhtml部分を切り出したファイル)
```php
<html>
～ 省略 ～
名前：<?php echo $full_name ?>
～ 省略 ～
</html>
```
#### 課題4
フォームに入力された項目を保持するクラスを下記ルールに従って設計、実装してください。

- 完全コンストラクタパターンを用いること
- フルネームを取得するメソッドを実装すること
- 1クラス1ファイルに分割すること(クラス名がProfileであれば、profile.phpというファイル名とする)

また、今回作成したクラスを用い表示処理を行ってください。

#### (例
```php
$profile = new Profile($_POST['mail_address']);
```

```php
<html>
～ 省略 ～
メールアドレス：<?php echo $profile->getMailAddress() ?>
～ 省略 ～
</html>
```

**Comment by thori0908** [comment]
#### 課題1
下記用語について調べてください。
- オブジェクト
- クラス
 - プロパティ
 - メソッド
 - コンストラクタ/デストラクタ
 - カプセル化
- インスタンス化
- アクセス修飾子
- abstract修飾子
- staticキーワード
- getter/setter
- 継承
 - オーバーライド
 - parent

**Comment by fr-itaya** [comment]
確認しました、課題1OKです！

**Comment by fr-matsuo** [comment]
* getter/setter

直接アクセスできてしまうと、カプセル化する意味がなくなってしまいます。
基本的に、カプセル化したプロパティにアクセスするものなので、どう関係があるか調べてみましょう。

**Comment by thori0908** [comment]
#### 課題1

- オブジェクト
：クラスから生成したインスタンスを参照代入したもの．

- クラス
：インスタンスを作成するために，プロパティとメソッドが定義されたもの．

 - プロパティ
：クラス内で保持される変数．クラス定義時に定義される．

 - メソッド
：クラス内で定義される処理．

 - コンストラクタ/デストラクタ
：クラスのインスタンス作成時や削除時に，自動的に呼ばれるメソッド．

 - カプセル化
：アクセス修飾子によって，クラス外からプロパティへのアクセスを，制限すること．

- インスタンス化
：クラスからnew演算子によって，実体を作成すること

- アクセス修飾子
：クラスの外側や内側からの参照など，メソッドやプロパティにアクセス可能な範囲を示す修飾子．修飾子にはpublic，private， protectedがある．

- abstract修飾子
：子クラスで必ず実装する必要がある親クラスのメソッドが，子クラスで実装されない場合，エラーを表示し，子クラスで実装すべきメソッドを明確にする．
Ref.
http://www.tohoho-web.com/java/modifier.htm

- staticキーワード
：インスタンス化せず，クラスのプロパティやメソッドにアクセスするときに用いる．

- getter/setter
：カプセル化したプロパティを，取得するgetメソッドや設定するgetメソッドを作成することによって，直接アクセスすること．
Ref.
http://redline.hippy.jp/lab/php/php_settergetter.php

- 継承
：指定するクラスのメソッドやプロパティを引き継ぎ，新たなクラスを定義すること．
 - オーバーライド
：親クラスで定義されたメソッドやプロパティを，子クラスを再定義することによって，上書きすること．

 - parent
：子クラスから親クラスのコンストラクタを呼び出すときに使う．

#### 課題2
require
：指定したファイルを読み込む，読み込みに失敗した場合，エラーを表示し，処理が停止する．

require_once
：requireとほぼ同様．すでに読み込まれたファイルの場合は読み込まれない．

include
：指定したファイルを読み込む，読み込みに失敗した場合，警告を表示するが，処理は続行される

include_once
：

**Comment by fr-matsuo** [comment]
確認しました、課題2までOKです。

**Comment by fr-itaya** [comment]
課題2迄確認しました、引き続き進めて下さい～

**Comment by fr-matsuo** [comment]
#54 で完了したのでクローズします。
