### ISSUE TITLE
サーバサイド - Apache - Apacheを理解する

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#32]
### ■目的

WebサーバやApacheについて理解します。

### ■課題

以下について調べて下さい。

- Apacheの概要
- モジュール
- プロセス
- ポート番号
- VirtualHost
- DocumentRoot
- DirectoryIndex
- MIME
- AddType

**Comment by thori0908** [comment]
- Apacheの概要
- モジュール
- プロセス
- ポート番号
- VirtualHost
- DocumentRoot
- DirectoryIndex
- MIME
- AddType

**Comment by fr-matsuo** [comment]
確認しました、OKです。

**Comment by fr-itaya** [comment]
確認してOKでした。お疲れ様でした！
