### ISSUE TITLE
サーバサイド - Apache - VirtualHostを設定する

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#33]
### ■目的

設定ファイルを編集しVirtualHostを設定します。  
※すでにApacheのインストール、設定ファイルは対応済みの状態という前提

### ■課題

Apacheの設定ファイル、補助設定ファイルを編集してVirtualHostを設定して下さい。  
設定する際には作業ログを残し、Issueには残さず個別に研修担当者に共有して下さい。

- Apacheの設定ファイル、補助設定ファイルの編集([バックアップ](https://github.com/fact-real/developers_training_public/wiki/%E3%83%90%E3%83%83%E3%82%AF%E3%82%A2%E3%83%83%E3%83%97)を取る事)
- Apacheの起動テスト確認
- Apacheの再起動
- Apacheの動作確認

**Comment by thori0908** [comment]
```
apache configtest

apache restart
```

**Comment by fr-sasaki** [comment]
作業ログを共有してもらったのでクローズします
