### ISSUE TITLE
サーバサイド - フレームワーク - フレームワークとは

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#34]
### ■目的

フレームワークについて理解する

### ■課題

以下について調べて下さい。

- フレームワークとは
- フレームワークのメリット、デメリット
- MVCモデルとは
- M、V、Cそれぞれの役割
- テンプレートエンジン

**Comment by thori0908** [comment]
- フレームワークとは

- フレームワークのメリット、デメリット

- MVCモデルとは
インターフェイスを持つアプリケーションソフトウェアの設計パターン
http://ja.wikipedia.org/wiki/Model_View_Controller

http://sp.e-words.jp/w/MVC.html

- M、V、Cそれぞれの役割
Model 
メインの処理

View 
表示 出力
Modelからデータを受け取り、HTMLページで表示する

Controller 
ユーザーからの入力を受け取る

- テンプレートエンジン

**Comment by fr-itaya** [comment]
確認しました、OKです！

**Comment by fr-matsuo** [comment]
確認しました、OKですー
