### ISSUE TITLE
サーバサイド - フレームワーク - Laravel - インストールと設定

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#35]
Laravelは最近トレンドになっているPHPのフレームワークです。  
ここではLaravelを触るのを通じてフレームワークについて学びます。  
Laravelを調べる時は公式サイトなどを活用して下さい。  

- [公式サイト](http://laravel.com/)
- [日本語ドキュメント](http://laravel4.kore1server.com/docs)
- [魔法少女Laravel(Laravelについての発表資料)](http://www.slideshare.net/KenichiMukai/php-study68)

なお、研修ではLaravel4.x系を使います。Laravel3.x系とは挙動が異なるため、調べる際には注意して下さい。

### ■目的

Laravelのインストール(プロジェクト作成)と初期設定について学びます。

### ■課題

`composer`コマンドを用いて、`$HOME/public_html/`直下に`laravel_training`というフォルダ名でLaravelをインストールして下さい。  
(Laravelのインストーラーは設定済みです)  
インストールしたらLaravelの公式サイトを参考に初期設定と #36 のVHを設定し、ブラウザで以下ページを確認出来るようにして下さい。

![](https://raw.github.com/fact-real/developers_training_public/master/sample/image/laravel.png)

確認出来たら、GitHubでLaravel用のリポジトリを作成し`laravel_training`をGitHubで管理するように設定して下さい。

**Comment by thori0908** [comment]
Ref.
http://kohkimakimoto.github.io/getcomposer.org_doc_jp/doc/00-intro.html

**Comment by fr-matsuo** [comment]
確認しました、OKです。

**Comment by fr-itaya** [comment]
確認しました。OKです！お疲れ様でした。
