### ISSUE TITLE
サーバサイド - フレームワーク - Laravel - テンプレートエンジンのBladeを使う

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#37]
### ■目的

Laravelで採用しているBladeを用いて、テンプレートエンジンについて学びます。

### ■課題

LaravelではテンプレートエンジンにBladeを採用しています。  
前課題で作成した静的HTMLをBladeにし以下を対応して下さい。

- 確認画面でフォームで入力した値を表示
- 確認画面からフォームへ戻ったら入力値を復帰
- `<? echo $name; ?>`といったPHP構文をviewで使わない
- routingとBladeを用いて値の表示、復帰を対応
- Bladeの書き方に関しては[ここ辺り](http://laravel4.kore1server.com/docs/templates)を参照

対応したらGitHubのPRを共有して下さい。

**Comment by thori0908** [comment]
http://laravel3.kore1server.com/docs/views/templating

**Comment by thori0908** [comment]
- ビューとデータの結合
http://laravel3.kore1server.com/docs/views#binding-data-to-views

**Comment by fr-matsuo** [comment]
↑完了したのでクローズします、お疲れ様でした。
