### ISSUE TITLE
サーバサイド - フレームワーク - Laravel - Controller作成

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#38]
### ■目的

LaravelのControllerを作成してMVCのCについて学びます。

### ■課題

Controllerを作成し、routing内で行っていた値の取得やアサインを全てControllerで行って下さい。  
routingには`Route::get('user/{id}', 'UserController@showProfile');`のようにメソッド、URL、Controllerのみを定義して下さい。  
対応したらGitHubのPRで共有して下さい。

**Comment by thori0908** [comment]
http://laravel3.kore1server.com/docs/controllers
