### ISSUE TITLE
サーバサイド - フレームワーク - Laravel - フォームのバリデーション、CSRF対策

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#39]
### ■目的

Laravelでのフォームバリデーション、CSRF対策について学びます。

### ■課題

[PHP > フォーム作成](https://github.com/fact-real/developers_training_public/wiki/%E9%96%8B%E7%99%BA%E7%A0%94%E4%BF%AE-php#wiki-%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%E4%BD%9C%E6%88%90)と同様の対応をLaravelを用いて対応して下さい。  
対応したらGitHubのPRで共有して下さい。

**Comment by thori0908** [comment]
http://laravel3.kore1server.com/docs/validation#validation-rules

**Comment by fr-itaya** [comment]
クローズします！
