### ISSUE TITLE
フロントエンド - JavaScript/jQuery - JavaScript/jQueryを理解する

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#40]
### ■目的

JavaScript、jQueryについて理解してもらいます。

### ■課題

以下について調べて下さい。

- JavaScriptとは
- jQueryとは
- JavaScriptとjQueryの違い
- オブジェクトとは

合わせて、下記にも一通り目を通してください。
http://dotinstall.com/lessons/basic_chrome_dev_v2

**Comment by thori0908** [comment]
JavaScriptとは

jQueryとは

JavaScriptとjQueryの違い

オブジェクトとは

**Comment by fr-matsuo** [comment]
確認しました、OKですー

**Comment by fr-itaya** [comment]
確認しました、OKです！お疲れ様でした。
