### ISSUE TITLE
ruby - 環境構築

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#59]
## ■目的
Rubyの開発環境を作れるようになる。 gemなどの、Ruby開発に必要な知識を身に着ける。

## キーワード
- rvm
- rbenv
- irb
- gem

## 課題1
- キーワードについて調べてください。
- rvm と rbenv の違いについて調べてください。

## 課題2
- rbenv + ruby-build をインストールしてください
 - インストールに使ったコマンドを貼り付けてください

## 課題3
- rbenv を用いて rubyのバージョン1.9.3と最新バージョンをインストールしてください。
 - インストールに使ったコマンドを貼り付けてください
- `hello world`を出力してください。irb、helloworld.rb どちらでも大丈夫です。

## 課題4
- `gem`コマンドからpryとawesome_printをインストールしてください
 - インストールに使ったコマンドを貼り付けてください

**Comment by thori0908** [comment]
#### 課題1
rvm
rbenv
irb
gem

**Comment by fr-matsuo** [comment]
課題1確認しました、OKです。

**Comment by thori0908** [comment]
課題2


```
# rbenv install
$ git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
```

**Comment by fr-itaya** [comment]
## 課題1
確認しました、OKです！

## 課題2
環境構築の際は、インストールしたツールのバージョン確認まで行なうようにしましょう。
バージョン確認のコマンドと、その結果も貼って頂けますか？

**Comment by thori0908** [comment]
```
# install ruby 1.9.3-p551
$ rbenv install -v 1.9.3-p551
```

**Comment by thori0908** [comment]
```
# pry install in 1.9.3-p551  
$ rbenv global 1.9.3-p551
$ rbenv version
1.9.3-p551 (set by /home/hori/.rbenv/version)
$ gem install pry pry-doc

# pry install in 2.2.2  
$ rbenv global 2.2.2
$ rbenv version
2.2.2 (set by /home/hori/.rbenv/version)
$ gem install pry pry-doc
```
Ref.
http://www.sitepoint.com/rubyists-time-pry-irb/

**Comment by fr-matsuo** [comment]
確認しました、OKですー
***
課題3

* irbでhello worldを出力

の`hello world=> nil`についてですが、irb は実行結果の返り値を自動的に出力するため、
`print "hello world"`で`hello world`を出力後、その返り値`nil`を続けて出力しています。

**Comment by fr-itaya** [comment]
確認しました。OKです！お疲れ様でした。
