### ISSUE TITLE
Linux - tmux - tmuxでのセッション管理

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#7]
### ■目的

tmuxでのデタッチ・アタッチをしセッション管理を学びます。

### ■課題

以下操作を実行して下さい。調べたコマンドやキーはIssueに記述して下さい。

- セッションの作成
- セッションのデタッチ
- セッションの確認
- セッションをアタッチ
- セッションの削除
- 全てのセッションを終了

**Comment by thori0908** [comment]
- セッションの作成
- セッションのデタッチ
- セッションの確認
- セッションをアタッチ
- セッションの削除
- 全てのセッションを終了

**Comment by fr-itaya** [comment]
確認しました。OKです！

**Comment by fr-matsuo** [comment]
確認しましたー
