### ISSUE TITLE
Linux - tmux - tmuxのカスタマイズ

### ISSUE THREAD

**Issue by fr-sasaki** [thori0908/training#8]
### ■目的

tmuxを見やすく使いやすくするよう、カスタマイズする方法を学びます。

### ■課題

`.tmux.conf`を編集し、自分が見やすく使いやすくなるようカスタマイズしてみて下さい。  
例えば、以下のカスタマイズ例があります。

- prefix keyの変更
- ステータスラインのレイアウト
- ペインのボーダーライン
- etc

また、他の開発者が公開している`dotfiles`などを参考してみるのもよいと思います。  
https://github.com/tokorom/dotfiles/blob/master/.tmux.conf  
https://github.com/chocoby/dotfiles/blob/master/.tmux.conf

**Comment by thori0908** [comment]
tmuxのバッファスクロールを設定。
https://github.com/thori0908/dotfiles/blob/master/.tmux.conf

Ref,
http://qiita.com/vintersnow/items/2880cc7b63a93a4d1b1d

**Comment by fr-itaya** [comment]
確認しました、OKです！
お時間のある時に色々設定を追加してみてもいいかもしれません。

**Comment by fr-matsuo** [comment]
スクロール確認しました、OKですー
